-- This is an empty migration file that serves as a baseline
-- It marks the current database state as the starting point for future migrations

-- CreateTable
CREATE TABLE `business` (
    `BUSINESS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NOT NULL,
    `BUSINESS_NAME` VARCHAR(255) NULL,
    `SHORT_NAME` VARCHAR(20) NULL,
    `DESCRIPTION` VARCHAR(1000) NULL,
    `ADDRESS_STREET` VARCHAR(100) NULL,
    `ADDRESS_ZIP` BIGINT NULL,
    `ADDRESS_CITY_ID` INTEGER NULL,
    `ADDRESS_TOWN` VARCHAR(100) NULL,
    `ADDRESS_COUNTRY` VARCHAR(100) NULL,
    `PHONE_NUMBER` VARCHAR(45) NULL,
    `PHONE_NUMBER_SHORT` VARCHAR(45) NULL,
    `WHATSAPP_NUMBER` VARCHAR(45) NULL,
    `WEB_ADDRESS` VARCHAR(1000) NULL,
    `LOGO` VARCHAR(255) NULL,
    `FACEBOOK_LINK` VARCHAR(1000) NULL,
    `INSTA_LINK` VARCHAR(1000) NULL,
    `TIKTOK_LINK` VARCHAR(1000) NULL,
    `GOOGLE_PROFILE` VARCHAR(1000) NULL,
    `IMAGE_URL` VARCHAR(1000) NULL,
    `GOOGLE_RATING` VARCHAR(10) NULL,
    `WHATSAPP_LINK` VARCHAR(255) NULL,
    `APPROVED` TINYINT NULL DEFAULT 0,
    `STATUS` TINYINT NULL DEFAULT 0,

    PRIMARY KEY (`BUSINESS_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `business_2_business_category` (
    `BUSINESS_BUSINESS_CATEGORY_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `BUSINESS_ID` BIGINT NULL,
    `BUSINESS_CATEGORY_ID` BIGINT NULL,
    `STATUS` TINYINT NULL,
    `DISPLAY_SEQ` INTEGER NULL,

    PRIMARY KEY (`BUSINESS_BUSINESS_CATEGORY_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `business_2_food_type` (
    `BUSINESS_FOOD_TYPE_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `BUSINESS_ID` BIGINT NULL,
    `FOOD_TYPE_ID` BIGINT NULL,

    PRIMARY KEY (`BUSINESS_FOOD_TYPE_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `business_category` (
    `BUSINESS_CATEGORY_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `CATEGORY_NAME` VARCHAR(100) NULL,

    PRIMARY KEY (`BUSINESS_CATEGORY_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `business_owner` (
    `BUSINESS_OWNER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NOT NULL,
    `EMAIL_ADDRESS` VARCHAR(255) NOT NULL,
    `PASSWORD` VARCHAR(45) NOT NULL,
    `FIRST_NAME` VARCHAR(100) NULL,
    `LAST_NAME` VARCHAR(100) NULL,
    `MOBILE_PHONE` VARCHAR(45) NULL,
    `ADDRESS_STREET` VARCHAR(100) NULL,
    `ADDRESS_NO` INTEGER NULL,
    `ADDRESS_ZIP` BIGINT NULL,
    `ADDRESS_TOWN` VARCHAR(100) NULL,
    `ADDRESS_COUNTRY` VARCHAR(100) NULL,
    `PIC` VARCHAR(255) NULL,

    UNIQUE INDEX `CUSTOMER_ID_UNIQUE`(`BUSINESS_OWNER_ID` ASC),
    UNIQUE INDEX `EMAIL_ADDRESS_UNIQUE`(`EMAIL_ADDRESS` ASC),
    PRIMARY KEY (`BUSINESS_OWNER_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `business_rating` (
    `BUSINESS_RATING_ID` BIGINT NOT NULL,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `BUSINESS_ID` BIGINT NULL,
    `BUSINESS_RATING` INTEGER NULL,

    PRIMARY KEY (`BUSINESS_RATING_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `business_reviews` (
    `BUSINESS_REVIEWS_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `REVIEWER_NAME` VARCHAR(255) NULL,
    `RATING` INTEGER NULL,
    `REVIEW` VARCHAR(1000) NULL,
    `PIC_1` VARCHAR(255) NULL,
    `PIC_2` VARCHAR(255) NULL,
    `PIC_3` VARCHAR(255) NULL,

    PRIMARY KEY (`BUSINESS_REVIEWS_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `city` (
    `CITY_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `CITY_CODE` VARCHAR(2) NULL,
    `CITY_NAME` VARCHAR(100) NULL,

    PRIMARY KEY (`CITY_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `city_town` (
    `CITY_TWON_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `CITY_ID` BIGINT NULL,
    `CITY_CODE` VARCHAR(2) NULL,
    `ZIPCODE` INTEGER NULL,
    `TOWN` VARCHAR(100) NULL,
    `E` DOUBLE NULL,
    `H` DOUBLE NULL,
    `LANGUAGE` TEXT NULL,

    PRIMARY KEY (`CITY_TWON_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `food_category` (
    `FOOD_CATEGORY_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `TITLE` VARCHAR(45) NULL,
    `DESCRIPTION` VARCHAR(255) NULL,

    PRIMARY KEY (`FOOD_CATEGORY_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `food_menu` (
    `FOOD_MENU_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `BUSINESS_ID` BIGINT NULL,
    `FOOD_CATEGORY_ID` BIGINT NULL,
    `TITLE` VARCHAR(255) NULL,
    `STATUS` TINYINT NULL,

    PRIMARY KEY (`FOOD_MENU_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `food_menu_items` (
    `FOOD_MENU_ITEMS_ID` BIGINT NOT NULL,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `FOOD_MENU_ID` BIGINT NULL,
    `MENU_CATEGORY_ID` BIGINT NULL,
    `TITLE` VARCHAR(100) NULL,
    `DESCRIPTION` VARCHAR(255) NULL,
    `PRICE` FLOAT NULL,
    `CURRENCY` VARCHAR(45) NULL,
    `PIC_1` VARCHAR(255) NULL,
    `PIC_2` VARCHAR(255) NULL,
    `PIC_3` VARCHAR(255) NULL,
    `APPROVED` TINYINT NULL,
    `DISPLAY` TINYINT NULL,

    PRIMARY KEY (`FOOD_MENU_ITEMS_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `food_type` (
    `FOOD_TYPE_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `TITLE` VARCHAR(45) NULL,
    `DESCRIPTION` VARCHAR(255) NULL,

    PRIMARY KEY (`FOOD_TYPE_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `foodeez_ranking` (
    `FOODEEZ_RANKING` INTEGER NOT NULL AUTO_INCREMENT,
    `foodeez_rankingcol` VARCHAR(45) NULL,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `BUSINESS_ID` INTEGER NULL,
    `RANKING` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`FOODEEZ_RANKING` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `foodeez_subscription` (
    `FOODEEZ_SUBSCRIPTION_ID` BIGINT NOT NULL,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `EMAIL_ADDRESS` VARCHAR(255) NULL,

    PRIMARY KEY (`FOODEEZ_SUBSCRIPTION_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `menu_category` (
    `MENU_CATEGORY_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `BUSINESS_ID` INTEGER NULL,
    `TITLE` VARCHAR(255) NULL,
    `SHOW` TINYINT NULL DEFAULT 1,
    `DISPLAY_SEQ` INTEGER NULL,

    PRIMARY KEY (`MENU_CATEGORY_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `owner_2_business` (
    `CUSTOMER_BUSINESS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `BUSINESS_OWNER_ID` BIGINT NULL,
    `BUSINESS_ID` BIGINT NULL,
    `STATUS` TINYINT NULL,

    PRIMARY KEY (`CUSTOMER_BUSINESS_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `visitors_account` (
    `VISITORS_ACCOUNT_ID` BIGINT NOT NULL,
    `CREATION_DATETIME` DATETIME(0) NULL,
    `EMAIL_ADDRESS` VARCHAR(255) NULL,
    `PASSWORD` VARCHAR(45) NULL,
    `FIRST_NAME` VARCHAR(45) NULL,
    `LAST_NAME` VARCHAR(45) NULL,
    `LANGUAGE` VARCHAR(45) NULL,
    `PIC` VARCHAR(255) NULL,

    PRIMARY KEY (`VISITORS_ACCOUNT_ID` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

